apiVersion: batch/v1
kind: Job
metadata:
  name: matverseny-backend-migration
spec:
  template:
    spec:
      containers:
        - name: matverseny-backend-migration
          image: ghcr.io/verseghy/matverseny-migration
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: postgres-pguser-postgres
      restartPolicy: OnFailure