services:
  db:
    image: docker.io/postgres:16
    environment:
      POSTGRES_USER: matverseny
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: matverseny
    ports:
      - 5432:5432

  nats:
    image: docker.io/nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222

  iam:
    pull_policy: always
    image: ghcr.io/verseghy/iam:v2
    environment:
      DATABASE_URL: postgres://iam:secret@iam-database:5432/iam
    ports:
      - 3001:3001
    depends_on:
      iam-migration:
        condition: service_completed_successfully

  iam-database:
    image: docker.io/postgres:16
    environment:
      POSTGRES_USER: iam
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: iam
    ports:
      - 5433:5432
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "iam"]
    #   interval: 10s
    #   timeout: 45s
    #   retries: 10

  iam-migration:
    pull_policy: always
    image: ghcr.io/verseghy/iam-migration:v2
    environment:
      DATABASE_URL: postgres://iam:secret@iam-database:5432/iam
    command: ["./iam-migration", "--verbose"]
    # depends_on:
    #   iam-database:
    #     condition: service_healthy
