version: '3.1'
services:
  service:
    build: .
    restart: on-failure
    depends_on:
      - mongo
    environment:
      - "MONGO_URI=mongodb://mongo:27017"
  mongo:
    image: mongo:4.4
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
    - "27017:27017"
  proxy:
    image: envoyproxy/envoy-dev:436946bb9df0acda0e4e709592205f0d199dfb79
    restart: on-failure
    depends_on:
      - service
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yml:/etc/envoy/envoy.yaml
