[package]
name = "matverseny-backend"
version.workspace = true
edition.workspace = true
publish.workspace = true
license-file.workspace = true
rust-version = "1.76"
default-run = "matverseny-backend"

[lints]
workspace = true

[dependencies]
axum = { version = "0.7.5", features = ["ws", "http2"] }
serde.workspace = true
tokio = { workspace = true, features = ["macros", "signal", "sync"] }
tower = "0.4.13"
tower-http = { version = "0.5.2", features = ["cors", "compression-full", "decompression-full", "catch-panic", "sensitive-headers", "request-id", "util", "normalize-path"] }
tracing.workspace = true
tracing-subscriber.workspace = true
entity.workspace = true
sea-orm.workspace = true
serde_json.workspace = true
validator = { version = "0.18.1", features = ["derive"] }
jsonwebtoken = "9.1.0"
rand = "0.8.5"
futures.workspace = true
rand_chacha = "0.3.1"
serde_with = "3.4.0"
tokio-tungstenite.workspace = true
sqlx = { version = "0.7.2", default-features = false, features = ["postgres"] }
uuid.workspace = true
bytes = "1.5.0"
mime = "0.3.17"
macros.workspace = true
smallvec = "1.11.1"
const_format.workspace = true
pin-project-lite = "0.2.13"
reqwest.workspace = true
libiam.workspace = true
chrono = { version = "0.4.31", features = ["serde"] }
async-nats = "0.35.1"
headers = "0.4.0"
anyhow = "1.0.86"

[dev-dependencies]
test-utils.workspace = true
