[package]
name = "entity"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
sea-orm = { version = "0.9.2", default-features = false, features = ["runtime-tokio-rustls", "sqlx-postgres", "macros", "with-chrono"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_repr = "0.1.9"
