[package]
name = "entity"
version.workspace = true
edition.workspace = true
publish.workspace = true
license-file.workspace = true

[dependencies]
sea-orm = { version = "0.10.4", default-features = false, features = ["runtime-tokio-rustls", "sqlx-postgres", "macros", "with-uuid"] }
serde = { version = "1.0.148", features = ["derive"] }
serde_repr = "0.1.9"
uuid.workspace = true
