apiVersion: batch/v1
kind: Job
metadata:
  name: iam-migrations
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
        - name: iam-migrations
          image: verseghy/iam-migration:latest
          imagePullPolicy: Always
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: mysql-password
            - name: DATABASE_URL
              value: mysql://root:$(DB_PASSWORD)@mysql.iam.svc.cluster.local/iam
      restartPolicy: OnFailure
  backoffLimit: 4