apiVersion: batch/v1
kind: Job
metadata:
  name: iam-migrations
spec:
  template:
    spec:
      containers:
        - name: iam-migrations
          image: ghcr.io/verseghy/iam-migration
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: mysql
          env:
            - name: DATABASE_URL
              value: mysql://root:$(MYSQL_ROOT_PASSWORD)@mysql.matverseny-backend.svc.cluster.local/iam # TODO: namespace?
      restartPolicy: OnFailure