apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: matverseny-backend
spec:
  kafka:
    template:
      podDisruptionBudget:
        maxUnavailable: 0
    version: 3.4.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.4"
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: true
  zookeeper:
    template:
      podDisruptionBudget:
        maxUnavailable: 0
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    template:
      topicOperatorContainer:
        env:
          - name: STRIMZI_USE_ZOOKEEPER_TOPIC_STORE
            value: "true"