apiVersion: apps/v1
kind: Deployment
metadata:
  name: matverseny-backend
  namespace: matverseny
spec:
  replicas: 3
  selector:
    matchLabels:
      app: matverseny-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: matverseny-backend
    spec:
      containers:
        - name: app
          image: verseghy/matverseny-backend
          ports:
            - containerPort: 3002
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /liveness
              port: 3002
            initialDelaySeconds: 300
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 3002
            initialDelaySeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              memory: 128Mi
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: postgres-pguser-postgres
            - name: IAM_APP_SECRET
              valueFrom:
                secretKeyRef:
                  key: IAM_APP_SECRET
                  name: matverseny-backend
            - name: IAM_URL
              value: http://iam.iam.svc.cluster.local
            - name: IAM_JWT_RSA_PUBLIC
              valueFrom:
                secretKeyRef:
                  key: public-key
                  name: jwt
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-cluster-kafka-bootstrap.matverseny.svc.cluster.local:9092
---
apiVersion: v1
kind: Service
metadata:
  name: matverseny-backend
  namespace: matverseny
spec:
  selector:
    app: matverseny-backend
  ports:
    - name: matverseny-backend
      protocol: TCP
      port: 80
      targetPort: 3002
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: matverseny-backend
  namespace: matverseny
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: matverseny-backend