// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: superadmin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start string `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End   string `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *SetTimeRequest) Reset() {
	*x = SetTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_superadmin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTimeRequest) ProtoMessage() {}

func (x *SetTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_superadmin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTimeRequest.ProtoReflect.Descriptor instead.
func (*SetTimeRequest) Descriptor() ([]byte, []int) {
	return file_superadmin_proto_rawDescGZIP(), []int{0}
}

func (x *SetTimeRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *SetTimeRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

type SetTimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetTimeResponse) Reset() {
	*x = SetTimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_superadmin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTimeResponse) ProtoMessage() {}

func (x *SetTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_superadmin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTimeResponse.ProtoReflect.Descriptor instead.
func (*SetTimeResponse) Descriptor() ([]byte, []int) {
	return file_superadmin_proto_rawDescGZIP(), []int{1}
}

var File_superadmin_proto protoreflect.FileDescriptor

var file_superadmin_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x75, 0x70, 0x65, 0x72, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x73, 0x75, 0x70, 0x65, 0x72, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x22, 0x38,
	0x0a, 0x0e, 0x53, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x52, 0x0a, 0x0a, 0x53,
	0x75, 0x70, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x44, 0x0a, 0x07, 0x53, 0x65, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x2e, 0x73, 0x75, 0x70, 0x65, 0x72, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x73, 0x75, 0x70, 0x65, 0x72, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x53, 0x65,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x09, 0x5a, 0x07, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_superadmin_proto_rawDescOnce sync.Once
	file_superadmin_proto_rawDescData = file_superadmin_proto_rawDesc
)

func file_superadmin_proto_rawDescGZIP() []byte {
	file_superadmin_proto_rawDescOnce.Do(func() {
		file_superadmin_proto_rawDescData = protoimpl.X.CompressGZIP(file_superadmin_proto_rawDescData)
	})
	return file_superadmin_proto_rawDescData
}

var file_superadmin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_superadmin_proto_goTypes = []interface{}{
	(*SetTimeRequest)(nil),  // 0: superadmin.SetTimeRequest
	(*SetTimeResponse)(nil), // 1: superadmin.SetTimeResponse
}
var file_superadmin_proto_depIdxs = []int32{
	0, // 0: superadmin.SuperAdmin.SetTime:input_type -> superadmin.SetTimeRequest
	1, // 1: superadmin.SuperAdmin.SetTime:output_type -> superadmin.SetTimeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_superadmin_proto_init() }
func file_superadmin_proto_init() {
	if File_superadmin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_superadmin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_superadmin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetTimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_superadmin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_superadmin_proto_goTypes,
		DependencyIndexes: file_superadmin_proto_depIdxs,
		MessageInfos:      file_superadmin_proto_msgTypes,
	}.Build()
	File_superadmin_proto = out.File
	file_superadmin_proto_rawDesc = nil
	file_superadmin_proto_goTypes = nil
	file_superadmin_proto_depIdxs = nil
}
