name: CI

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches:
    - master
  pull_request: {}

jubs:
  check:
    name: Check
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Check
        run: cargo clippy --all
      - name: Format
        run: cargo fmt --all -- --check

  test:
    name: Test
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Setup environment
        run: docker compose up -d
      - uses: Swatinem/rust-cache@v1
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

  cargo-deny-check:
    name: cargo-deny check
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check ${{ matrix.checks }}
