name: Integration test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Start services
        run: make docker-d && sleep 60

      - name: Run tests
        run: make int-run
