permissions:
  contents: read

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

name: test

env:
  CARGO_TERM_COLOR: always

jobs:
  required:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Setup environment
        run: docker compose up -d
      - name: cargo nextest run
        run: cargo nextest run
        env:
          IAM_URL: http://127.0.0.1:3001
          IAM_APP_SECRET: QXBwSUQtNzAwNzk1N2QtN2Q5OC0xMWVlLTg4NTktNzY2NTY0MDAwMDAwOndhdDRUSGdwcEJJdWExa095Z3R5R3hpU3hpRkVSZFZ4
          NATS_URL: 127.0.0.1
